---
# TODO
# SUP
# marjory
engines:
  rubocop:
    enabled: true
  fixme:
    enabled: true
    exclude_paths:
      - config/engines.yml
      - .codeclimate.yml
  fixme:
    enabled: true

ratings:
  paths:
  - "**.rb"
exclude_paths:
  - .bundle/
  - spec/**/*
  - benchmarks/**/*
