inherit_from: base_rubocop.yml

AllCops:
  TargetRubyVersion: 2.5

Lint/Debugger:
  Exclude:
  - lib/cc/cli/console.rb

Style/SpecialGlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
