#!/bin/sh
invalid_setup() {
  local reason=$1

  cat >&2 <<EOF
Your Docker setup does not support the codeclimate wrapper script:

  > $reason

We require a local Docker daemon that supports communication via the default
socket path.

Please use \`docker run' to run the \`codeclimate/codeclimate' image directly.

See https://github.com/codeclimate/codeclimate for more details.

EOF
  exit 1
}

docker_for_mac() {
  test -S /var/tmp/docker.sock > /dev/null 2>&1
}

socket_missing() {
  invalid_setup "$socket_path must exist as a Unix domain socket"
}

invalid_docker_host() {
  local host=$1

  invalid_setup "invalid DOCKER_HOST=$host, must be unset or unix://$socket_path"
}

socket_path=/var/run/docker.sock

if docker_for_mac; then
  socket_path=/var/tmp/docker.sock
fi

if [ -n "$DOCKER_MACHINE_NAME" ] && command -v docker-machine > /dev/null 2>&1; then
  docker-machine ssh $DOCKER_MACHINE_NAME -- \
    test -S /var/run/docker.sock > /dev/null 2>&1 || socket_missing

  docker-machine ssh $DOCKER_MACHINE_NAME -- \
    'test -n "$DOCKER_HOST" -a "$DOCKER_HOST" != "unix:///var/run/docker.sock"' > /dev/null 2>&1 \
    && invalid_docker_host $(docker-machine ssh $DOCKER_MACHINE_NAME -- 'echo "$DOCKER_HOST"')
else
  test -S $socket_path || socket_missing
  test -n "$DOCKER_HOST" -a "$DOCKER_HOST" != "unix://$socket_path" \
    && invalid_docker_host "$DOCKER_HOST"
fi

docker_run() {
  exec docker run \
    --interactive --rm \
    --env CODECLIMATE_CODE \
    --env CODECLIMATE_TMP \
    --env CODECLIMATE_DEBUG \
    --env CONTAINER_MAXIMUM_OUTPUT_BYTES \
    --env CONTAINER_TIMEOUT_SECONDS \
    --env ENGINE_MEMORY_LIMIT_BYTES \
    --volume "$CODECLIMATE_CODE":/code \
    --volume "$CODECLIMATE_TMP":/tmp/cc \
    --volume "$socket_path":/var/run/docker.sock \
    "$@"
}

if [ -z "$CODECLIMATE_CODE" ]; then
  export CODECLIMATE_CODE=$PWD
fi

if [ -z "$CODECLIMATE_TMP" ]; then
  export CODECLIMATE_TMP=/tmp/cc
fi

if [ -t 0 ] && [ -t 1 ]; then
  docker_run --tty codeclimate/codeclimate "$@"
else
  docker_run codeclimate/codeclimate "$@"
fi
