#!/bin/sh
invalid_setup() {
  local reason=$1

  cat >&2 <<EOF
Your Docker setup does not support the codeclimate wrapper script:

  > $reason

We require a local Docker daemon that supports communication via the default
socket path.

Please use \`docker run' to run the \`codeclimate/codeclimate' image directly.

See https://github.com/codeclimate/codeclimate for more details.

EOF
  exit 1
}

socket_missing() {
  invalid_setup "/var/run/docker.sock must exist as a Unix domain socket"
}

invalid_docker_host() {
  local host=$1

  invalid_setup "invalid DOCKER_HOST=$host, must be unset or unix:///var/run/docker.sock"
}

if [ -n "$DOCKER_MACHINE_NAME" ] && command -v docker-machine > /dev/null 2>&1; then
  docker-machine ssh $DOCKER_MACHINE_NAME -- \
    test -S /var/run/docker.sock > /dev/null 2>&1 || socket_missing

  docker-machine ssh $DOCKER_MACHINE_NAME -- \
    'test -n "$DOCKER_HOST" -a "$DOCKER_HOST" != "unix:///var/run/docker.sock"' > /dev/null 2>&1 \
    && invalid_docker_host $(docker-machine ssh $DOCKER_MACHINE_NAME -- 'echo "$DOCKER_HOST"')
else
  test -S /var/run/docker.sock || socket_missing
  test -n "$DOCKER_HOST" -a "$DOCKER_HOST" != "unix:///var/run/docker.sock" \
    && invalid_docker_host "$DOCKER_HOST"
fi

CC_XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config/}
CC_XDG_CONFIG="${CC_XDG_CONFIG_HOME}/codeclimate/config.yml"
CC_XDG_CONFIG_DIR=$(dirname "${CC_XDG_CONFIG}")
[ -d "$CC_XDG_CONFIG_DIR" ] || mkdir -p "$CC_XDG_CONFIG_DIR"
[ -f "$CC_XDG_CONFIG" ] || ( echo "---" > "$CC_XDG_CONFIG" )

CC_XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache/}
CC_XDG_CACHE="${CC_XDG_CACHE_HOME}/codeclimate/cache.yml"
CC_XDG_CACHE_DIR=$(dirname "${CC_XDG_CACHE}")
[ -d "$CC_XDG_CACHE_DIR" ] || mkdir -p "$CC_XDG_CACHE_DIR"
[ -f "$CC_XDG_CACHE" ] || ( echo "---" > "$CC_XDG_CACHE" )

docker_run() {
  docker run \
    --interactive --rm \
    --env CODECLIMATE_CODE \
    --env CODECLIMATE_TMP \
    --env CODECLIMATE_DEBUG \
    --env CODECLIMATE_VERSIONS_URL \
    --env CONTAINER_MAXIMUM_OUTPUT_BYTES \
    --env CONTAINER_TIMEOUT_SECONDS \
    --env ENGINE_MEMORY_LIMIT_BYTES \
    --env XDG_CONFIG_HOME="/xdg/config" \
    --env XDG_CACHE_HOME="/xdg/cache" \
    --volume "$CODECLIMATE_CODE":/code \
    --volume "$CODECLIMATE_TMP":/tmp/cc \
    --volume "${CC_XDG_CONFIG}":/xdg/config/codeclimate/config.yml \
    --volume "${CC_XDG_CACHE}":/xdg/cache/codeclimate/cache.yml \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    "$@"
}

if [ -z "$CODECLIMATE_CODE" ]; then
  export CODECLIMATE_CODE=$PWD
fi

if [ -z "$CODECLIMATE_TMP" ]; then
  export CODECLIMATE_TMP=/tmp/cc
fi

if [ -t 0 ] && [ -t 1 ]; then
  docker_run --tty codeclimate/codeclimate "$@"
else
  docker_run codeclimate/codeclimate "$@"
fi
